[project]
name = "src"
version = "0.1.0"
description = "Manimation Repo Template"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "manim",
]

[tool.uv.workspace]
members = [
    "custom-mobjects",
]
